// Date: 17/05/2014 19:30:14
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package robomuss.rc.block.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelTrackSupport extends ModelBase
{
  //fields
   public  ModelRenderer middle;
    public  ModelRenderer top;
    public  ModelRenderer bottom;
  
  public ModelTrackSupport()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      middle = new ModelRenderer(this, 0, 0);
      middle.addBox(0F, 0F, 0F, 10, 16, 10);
      middle.setRotationPoint(-5F, 8F, -5F);
      middle.setTextureSize(128, 128);
      middle.mirror = true;
      setRotation(middle, 0F, 0F, 0F);
      top = new ModelRenderer(this, 0, 0);
      top.addBox(0F, 0F, 0F, 16, 1, 16);
      top.setRotationPoint(-8F, 23F, -8F);
      top.setTextureSize(128, 128);
      top.mirror = true;
      setRotation(top, 0F, 0F, 0F);
      bottom = new ModelRenderer(this, 0, 0);
      bottom.addBox(0F, 0F, 0F, 16, 1, 16);
      bottom.setRotationPoint(-8F, 8F, -8F);
      bottom.setTextureSize(128, 128);
      bottom.mirror = true;
      setRotation(bottom, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    middle.render(f5);
    top.render(f5);
    bottom.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
